### PR TITLE
https connection

### PR DESCRIPTION
**Pull request by astrnad**

### CODE REVIEW

**Comment by astrnad** [comment]
Testing shows that sse_client doesn't play nice with SSL connections which have a self-signed certificate in the path - needs more investigation.

**Comment by spacemanspiff2007** [comment]
Thank you for your PR!
Could you fix all errors? Does it work locally as expected?

**Comment by astrnad** [comment]
Yes, SSL openhab connection (with a self-signed certificate) seems to work fine, event subscription from OH too. I took some of your example rules from the docs, those worked fine and as documented, but i haven't done any extensive testing (yet), will do so when i try to port my jython27 rules from oh25 to habapp and oh3 :)

**Comment by astrnad** [comment]
Code formatting done, please run checks again

**Comment by spacemanspiff2007** [comment]
I've switched the config library in the dev branch and I incorporated your changes.
Unfortunately this can not be merged. 
But thank you very much for your contribution and testing - it made implementing it very easy!

**Pull request closed without merging**
