### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by Rosi2143**
Add options to automatically restart HABApp when openHAB is restarted

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
Thanks for the contribution!
Can you maybe add a small sentence that HABApp automatically reconnects and keeps the items in sync?
My concern that this could imply that it's required to restart HABApp when openhab changes.

**Comment by Rosi2143** [comment]
Hello @spacemanspiff2007,

but that's what it does - and this is also my experience .

HABApp fails to work - e.g. ping is not working anymore - if openHAB is restarted.

If this is not intended, should I raise a bug?

**Comment by spacemanspiff2007** [comment]
> If this is not intended, should I raise a bug?

This definitely sounds like a bug.
You should be able to restart openhab and HABApp should be working again without issues.
Could you please create an issue and attach a log or something. I'll take a look at it.

**Comment by Rosi2143** [comment]
Just as an info, I was still running the previous version ~4month old and just updated 2days ago. 

But I try it out and send you all logs. If the error happens again, I'll raise a bug.

Thanks.

**Pull request closed without merging**
