### PR TITLE
Add some new item functions

### PR DESCRIPTION
**Pull request by DerOetzi**
As I suggested after our discussion in #256 I added an is_empty property and some convenience functions for setting default values. Please see this PR as a suggestion. Give me some feedback, whether you want this functions if not will add this to my library.

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
Out of curiosity:
What is your use case for all these null values? 
I've persisted most of my items with map_db and the rest get set on a defined level when the rules get loaded.

**Comment by DerOetzi** [comment]
Of course you can ask. 

I have written a configuration creator https://github.com/DerOetzi/openhab_creator which allows me to do the basic modelling of a smarthome in very simple, versionable json-files. When running the creator it creates or updates the complete textual configuration directory of openhab like things, items, automation, sitemaps, etc.

The openhab-system which is configured by this enables the user to do much configuration via the BasicUI or Smartphone App, for example timebased scene system, assignment of motionsensors, wallswitches or eco and comfort-temperature.

For example I have at my home about 150 things and round about 2600 items.

My main target is to be able to give the possibility to re-setup the system from scratch within less then five minutes and reset it to an default configuration (especially useful for smarthome users like for example my parents ;) ). 

I thought long about two ways how to achieve the default configuration:
1. A "default-configuration rule which runs on system startup and set all empty values to defaults
2. Each rule ensures that it's needed configuration items are set to default value

Because first solution would be in my opinion a big business logic monolith which have to know about all other rules, I decided myself for the second solution, which lefts the business logic where it belongs to.

This means the default-functions will only do something on the very first run of a rule (or if a new device is added) after this most of the configuration is stored to mapdb. 

Hope this answers your question. 

As I said for me it is okay if you say this is in your eyes a very special corner case. Feel free to decline this PR in this case. I can although write me an util-function.

**Comment by spacemanspiff2007** [comment]
Sounds impressive! I tried to achieve the same by splitting configuration/rules in separate files and just merge these across installations. Then I use the HABApp parameter files to set everything up for the running instance.
But that just works for simpler things.

> 2\. Each rule ensures that it's needed configuration items are set to default value

```python
if item.value is None:
    item.oh_post_value(DEFAULT)
```

or just

```python
value = item.get_value(DEFAULT)
```

if you don't want to set it. I think the first one is something I'd be willing to implement.

> I can although write me an util-function.

With the new version of HABApp you'll be able to modify things before the startup. 
You then can just create a mixin for the Openhab Items and set the new classes as a default.
Then you don't have to use a library function and have no overhead.
For this case though a static function in the ``libs`` folder is enough.

**Comment by DerOetzi** [comment]
I'm not sure what you  mean with DEFAULT? Is it a keyword or just a constant I define? If it's a keyword where is the default value defined?

And by taking cleancode DRY into account, I think those two lines should be wrapped by a method of item class:

```python
if item.value is None:
  item.post_update(value)
```

**Comment by spacemanspiff2007** [comment]
> I'm not sure what you mean with DEFAULT? Is it a keyword or just a constant I define? If it's a keyword where is the default value defined?

It's the default value you want to set.

---

Now we just need a good name (that's the hardest part)
- ```item.post_value_on_none(default_value)```
- ```item.oh_set_on_none(default_value)```
- ```item.set_on_none(default_value)```
- ```item.oh_initialize(default_value)```
- ```item.initialize(default_value)```

Or it could be a more generic function.
- ```item.post_diff_value(value, compare_value=None)```
- ```item.post_different_value(value, compare_value=None)```
- ```item.oh_post_diff_value(value, compare_value=None)```
- ```item.oh_post_different_value(value, compare_value=None)```

I think the more generic function is better because it can be used to set a value conditionally.

**Comment by DerOetzi** [comment]
> > I'm not sure what you mean with DEFAULT? Is it a keyword or just a constant I define? If it's a keyword where is the default value defined?
> 
> It's the default value you want to set.
> 
> Now we just need a good name (that's the hardest part)
> 
> * `item.post_value_on_none(default_value)`
> * `item.oh_set_on_none(default_value)`
> * `item.set_on_none(default_value)`
> * `item.oh_initialize(default_value)`
> * `item.initialize(default_value)`
> 
> Or it could be a more generic function.
> 
> * `item.post_diff_value(value, compare_value=None)`
> * `item.post_different_value(value, compare_value=None)`
> * `item.oh_post_diff_value(value, compare_value=None)`
> * `item.oh_post_different_value(value, compare_value=None)`
> 
> I think the more generic function is better because it can be used to set a value conditionally.

I think some short named would be good for the the default one. First I thought oh_initialize and initialize would be good, but I'm  not sure whether they are misleading because they "intialize" only the value of the item and initialize sounds like something more configuration of an item.

So maybe we go with:

* `item.oh_post_if_different(value, compare_value=None)`  for OpenhabItem
* `item.post_if_different(value, compare_value=None)` for BaseValueItem

I can change my PR this evening if you confirm.

**Comment by spacemanspiff2007** [comment]
I had another one:
```item.conditional_post(value, compare_value)```

But then I thought it probably would be good to keep the names aligned with ``post_value`` and ``oh_post_update`` and just add a suffix.
So how about (oh functions accordingly)
- ``item.post_value_on_diff()``
- ``item.post_value_conditinally()``
- ``item.post_value_if_different()``


> I can change my PR this evening if you confirm.

Once we settled on a name I'll add it directly in HABApp. It's quick and if you rebase it's a lot of work for you.

**Comment by DerOetzi** [comment]
I would prefer Last one 

item.post_value_if_different()

So I'll Close this PR and revert my fork

Thanks in advance

**Comment by DerOetzi** [comment]
Sorry thought a second time on it

post_value_if_different is not the correct meaning, because it should to the post if actual value equals compare_value so maybe 

post_value_if_actual_is

**Comment by DerOetzi** [comment]
> With the new version of HABApp you'll be able to modify things before the startup. You then can just create a mixin for the Openhab Items and set the new classes as a default. Then you don't have to use a library function and have no overhead. For this case though a static function in the `libs` folder is enough.

Can you please give me an example how this works?

**Pull request closed without merging**
