### PR TITLE
added missing GroupItemStateChangedEventFilter

### PR DESCRIPTION
**Pull request by nobbi1991**
Added missing GroupItemStateChangedEventFilter. 
I use the filter already in my system :)

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
In the current dev branch I fixed the groups in anticipating for OH4.0.
There you can trigger on Groups with the `ValueUpdateEventFilter` and `ValueChangeEventFilter`.
Would you still think a dedicated `GroupItemStateChangedEventFilter` makes sense in that case?
Or wouldn't it be better to recommend the `ValueUpdateEvent` in the docs to the user?

**Comment by nobbi1991** [comment]
Hi,
no, for me it is still not clear, how to trigger on a group event. In the linked example I don't see an example for a group item :(
Can you please point out, which example you mean?

If you added support for the normal `ValueUpdateEventFilter` and `ValueChangeEventFilter` for group items, then we don't need my PR anymore ;)

**Comment by spacemanspiff2007** [comment]
Text in the Example:
```python
# This is the same as above but with the generic filter
my_item.listen_event(self.on_val_my_value, EventFilter(ValueUpdateEvent, value='my_value'))
```

How it already works

```python
my_item.listen_event(self.on_val_my_value, EventFilter(GroupItemStateChangedEventFilter, value='my_value'))
```

The `ItemStateEventFilter` is only a convenience filter. You can achieve the same by passing the event class into `EventFilter`



> If you added support for the normal `ValueUpdateEventFilter` and `ValueChangeEventFilter` for group items, then we don't need my PR anymore ;)

It will work as expected with the next release

**Comment by nobbi1991** [comment]
Ok, now I get it :)
From my side we can remove this PR. Thanks for clarification

**Pull request closed without merging**
